# This is a sample docker-compose file for setting up InfluxDB 2.0 and Telegraf

name: influxdb2-compose
services:
  # InfluxDB 2.0 service
  influxdb2:
    image: influxdb:latest
    container_name: influxdb2-container
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=1
      - DOCKER_INFLUXDB_INIT_BUCKET=data

  # Telegraf service
  telegraf:
    image: telegraf:latest
    container_name: telegraf-container
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb2

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  default:
    external: false


